//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US.AppointmentScheduling.RESTAPI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    }
}
